apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app
spec:
  selector:
    matchLabels:
      app: bully-app
  replicas: 4
  template:
    metadata:
      name: bully-app
      labels:
        name: bully-app
        app: bully-app
    spec:
      containers:
        - name: bully-container
          image: fortune_cookies:v0.0.8
          imagePullPolicy: Never
          env:
            - name: WEB_PORT
              value: "3000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector.default.svc.cluster.local:4317"
            
            # 2. This sets the service name (must match init_tracing)
            - name: OTEL_SERVICE_NAME
              value: "bully-app"

            # 3. This sets your log level for the console
            - name: RUST_LOG
              value: "info,fortune_cookies=debug" # Or whatever you called your crate
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
